languageCode = 'en-uk'
title = 'Invest in UK Logistics, Greater Lincolnshire provides logistics businesses with direct access to high-growth market opportunities, combined uniquely with world-class digitalisation and automation solutions.'

[params]
  contactdomain = 'https://investlincolnshire.co.uk/'
  imagedomain = 'https://res.cloudinary.com/lincs/image/upload/q_auto,f_auto/'

[module]
  [[module.imports]]
    path = "github.com/crescolincs/lincs-theme"

#Update hugo modules (in our case the theme)$> hugo mod get -u

#dev site https://dev.logistics-b3m.pages.dev

# for vercel and netlify we probably need the full 5 step process
#
# hugo mod init github.com/{your-github-account}/{your-hugo-site-repo} && 
# hugo mod get github.com/{your-github-account}/{your-static-site-repo} && 
# mv fullhugo.toml hugo.toml && 
# hugo mod vendor && 
# hugo --gc --minify

# for cloudflare pages lets try a shorter 2 step because it seems to understand hugo modules
# hugo mod get -u && hugo --gc --minify 